### ISSUE TITLE
Add option for secure input

### ISSUE THREAD

**Issue by vanshg** [TMiguelT/ArgparsePrompt#1]
Add a parameter to the parser such that instead of plaintext `input()`, it can utilize `getpass.getpass()` to get secure input

**Comment by multimeric** [comment]
Good idea

**Comment by multimeric** [comment]
This is now implemented: 6ce267c270c9d8ba03c5f2c913273e12ebb12ab2. Also, a release has been uploaded to PYPI

**Comment by vanshg** [comment]
Very cool, thank you!
