### ISSUE TITLE
Make Compatible With Python 2.7

### ISSUE THREAD

**Issue by pkenjora** [TMiguelT/ArgparsePrompt#2]
Hi,

  The original Argparse this extends is 2.7 compatible, and none of the code looks like it needs to be 3.0 only.  Any chance we can get a 2.7 version or a disclaimer that its 3.0 only?

Thanks!

**Comment by multimeric** [comment]
Sorry, I somehow missed this question when you asked it.

In general I'm not interested in making my work Python 2 compatible because it adds a lot of mess to the code, but since this is such a small codebase I would be open to a PR solve this.

**Comment by multimeric** [comment]
It has now been documented that ArgparsePrompt is only currently compatible with Python 3.6+
